/** @type {import("prettier").Options} */
const config = {
  arrowParens: 'avoid',
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  endOfLine: 'lf',
  htmlWhitespaceSensitivity: 'css',
  importOrder: [
    '^react(/.*)?$',
    '^next(/.*)?$',
    '<THIRD_PARTY_MODULES>',
    '^@/app(/.*)?$',
    '^@/components(/.*)?$',
    '^@/(/.*)?$',
    '.*\\.css$',
    '^[./]',
  ],
  importOrderSeparation: true,
  insertPragma: false,
  jsxSingleQuote: false,
  plugins: [
    'prettier-plugin-tailwindcss',
    '@trivago/prettier-plugin-sort-imports',
  ],
  printWidth: 80,
  proseWrap: 'always',
  quoteProps: 'as-needed',
  requirePragma: false,
  semi: false,
  singleAttributePerLine: false,
  singleQuote: true,
  tabWidth: 2,
  tailwindAttributes: ['class', 'className', 'ngClass', '.*[cC]lassName'],
  tailwindFunctions: ['clsx', 'cn'],
  trailingComma: 'all',
  useTabs: false,
}

export default config
