/** @type {import("prettier").Options} */
const config = {
  arrowParens: "always",
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: "auto",
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "css",
  importOrder: [
    "^react(/.*)?$",
    "^next(/.*)?$",
    "<THIRD_PARTY_MODULES>",
    "^@/app(/.*)?$",
    "^@/components(/.*)?$",
    "^@(/.*)?$",
    ".*\\.css$",
    "^[./]",
  ],
  importOrderSeparation: true,
  insertPragma: false,
  jsxSingleQuote: false,
  plugins: [
    "@trivago/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  printWidth: 80,
  proseWrap: "always",
  quoteProps: "as-needed",
  requirePragma: false,
  semi: false,
  singleAttributePerLine: true,
  singleQuote: false,
  tabWidth: 2,
  tailwindAttributes: ["class", "className", "ngClass", ".*[cC]lassName"],
  tailwindFunctions: ["clsx", "cn"],
  trailingComma: "all",
  useTabs: false,
}

export default config
